== Q1:代收付有，多渠道没有的数据该如何处理

=== 背景描述
代收付在发送数据时，有时会掉单，但代收付的GENERATION_PAYMENT 的状态已经变成2.

=== 操作方式
. 先根据ORDER_NO或者REQUEST_NO找出代收付BATCH_NO（见代收付交接文档4.1.1和4.1.2）
. 先将GENERATION_PAYMENT中的数据删除，记录下对应的TRANS_SUMMARY_ID
. 将对应的TRANS_DETAIL_SUMMARY 的状态更新成为1

[title=单笔例句]
```
DELETE FROM `payment`.GENERATION_PAYMENT WHERE GENERATION_ID IN ('2017071306115084', '2017071306115546', '2017071306115753');
UPDATE `payment`.TRANS_DETAIL_SUMMARY SET STATUS_ID = '1' WHERE TRANS_SUMMARY_ID IN ('11635944','11636347','11636589');
```

[title=批量例句]
```
DELETE FROM `payment`.GENERATION_PAYMENT WHERE BATCH_NO IN ('B2017092801011759479693');
UPDATE `payment`.TRANS_DETAIL_SUMMARY SET STATUS_ID = '1',EXPAND1 = '' WHERE EXPAND1 IN ('B2017092801011759479693');
```

== Q2:代收付历史表数据维护(不支持现在支付代付)

=== 背景描述
在按银行拆分批次上线后，导致代收付系统的数据切换定时任务（将数据从GENERATION_PAYMENT表中切到GENERATION_PAYMENT_HISTORY）对状态扫描不对，会将处理中的切入到历史表中

=== 操作方式
. 查出未返回结果的批次号,根据sql3
. 通过执行sql1，将数据从历史表GENERATION_PAYMENT_HISTORY切回交易表GENERATION_PAYMENT
. 通过执行sql2，将已经从历史表切到交易表的数据删除
. 通过多渠道结果回推界面，重新发送通知()
.. 多渠道登陆地址:http://oprsjf.rongcapital.com.cn:8094/GateRouter-web/logon/logon.do
.. 列表选择对应交易：代收选收款批次信息管理，代付选付款批次信息管理
.. 根据批次号筛选
.. 点击通知
. 检查数据

=== Sql内容

==== Sql1:
```
INSERT INTO GENERATION_PAYMENT
SELECT A.GENERATION_HISTORY_ID AS GENERATION_ID, A.BATCH_NO, B.TRANS_SUMMARY_ID, A.BUSSINESS_CODE, A.BUSSINESS_TYPE, A.ORG_CODE, A.ROOT_INST_CD, A.PRODUCT_ID, A.USER_ID, A.CERTIFICATE_NUMBER, A.CERTIFICATE_TYPE, A.ACCOUNT_NO, A.ACCOUNT_NAME, A.ACCOUNT_PROP, A.ACCOUNT_TYPE, A.BANK_CODE, A.BANK_NAME, A.PAY_BANK_CODE, A.PAY_BANK_NAME, A.PROVINCE, A.CITY, A.ORDER_NO, A.ORDER_TYPE, A.AMOUNT, A.CURRENCY, A.RET_CODE, A.ERR_MSG, A.STATUS_ID, A.REMARK, A.ACCOUNT_DATE, A.CREATED_TIME, A.UPDATED_TIME FROM GENERATION_PAYMENT_HISTORY A
INNER JOIN TRANS_DETAIL_SUMMARY B ON A.ORDER_NO = B.ORDER_NO AND A.AMOUNT = B.AMOUNT AND A.USER_ID = B.USER_ID AND A.BATCH_NO = B.EXPAND1
WHERE A.BATCH_NO IN ('B20171124120608343278677') AND A.STATUS_ID = '3';
```
==== Sql2:
```
DELETE FROM GENERATION_PAYMENT_HISTORY  WHERE BATCH_NO IN ('B20171124120608343278677') AND STATUS_ID = '3';
```

==== Sql3:
```
SELECT EXPAND1 FROM TRANS_DETAIL WHERE ORDER_NO IN ('OP20171201173513015') GROUP BY EXPAND1;
SELECT EXPAND1 FROM TRANS_DETAIL WHERE REQUEST_NO IN ('M00000406151202455007492486') AND STATUS_ID = '2' GROUP BY EXPAND1;
```

== Q3:订单现金贷日放款报表

=== 背景描述
提供给现金贷放款日手工对账

=== 操作方式
. 通过sql查询数据
. 生成excel
. 发送运营人员

=== Sql内容
[title=现金贷日报表]
```
SELECT OP.PAYMENT_ID,D.END_TIME FROM `order`.ORDER_INFO OI
INNER JOIN `order`.ORDER_PAYMENT OP ON OI.ORDER_ID = OP.RETRIREF_NO AND OP.STATUS_ID = '3'
INNER JOIN `loan`.LOAN_ORDER_INFO A ON A.USER_ID = OI.USER_ID AND OI.REMARK = A.ORDER_ID
INNER JOIN `loan`.LOAN_ORDER_INFO LOI ON A.USER_ID = LOI.USER_ID AND LOI.ORDER_TYPE_ID = 'M30001' AND LOI.ROOT_INST_CD='M000029' AND LOI.STATUS_ID = '41'
INNER JOIN `loan`.LOAN_ITEM B ON A.ORDER_ID = B.ORDER_ID AND B.ORDER_ITEM_TYPE_ID = 'M20005' AND B.STATUS_ID = '1'
INNER JOIN `loan`.LOAN_ITEM C ON A.ORDER_ID = C.ORDER_ID AND C.ORDER_ITEM_TYPE_ID = 'M20007' AND C.STATUS_ID = '1'
INNER JOIN `loan`.LOAN_ITEM D ON A.ORDER_ID = D.ORDER_ID AND D.ORDER_ITEM_TYPE_ID = 'M20004' AND D.STATUS_ID = '1' AND D.END_TIME IN (?)
WHERE
    A.ORDER_TYPE_ID = 'M20001'
    AND OI.ROOT_INST_CD = 'M000029'
    AND A.ROOT_INST_CD = 'M000029'
    AND A.STATUS_ID IN ('5','10')
    AND A.PROVIDER_ID = 'M00000X'
    GROUP BY A.ORDER_ID ;
```

== Q4: 运营提前还款操作

=== 背景描述
课栈的大机构有帮学员垫付的操作，量比较大，由运营人员操作成本太高，因此交于技术批量处理

=== 操作方式
. 从svn上pull下代码，svn地址：https://svn.in.dataengine.com/svn/RD/Development/Operation/Order/trunk/order-1.0.1
. 进行maven install:install 确保项目依赖包下载完毕
. 在rkylin-order-core模块下的resource中，找到fourthBatch_result，将运营人员提供的表格中的信息取出，总共四项信息从左到右一次为：订单号，用户id，应还款时间，应还款金额。 四项信息用","分割，日期格式为yyyy-MM-dd。
`````
Tips: 运营人员一般提供为excel格式，将多余列隐藏后，可直接复制粘贴出来。粘贴出来的内容为"\t"分割的4列，然后将分隔符"\t"替换为","，将日期格式规范，即可。
`````
. 找到com.rkylin.order.file.FileProcessor类，直接运行，等待运行结束即可。

== Q5: 运营线下还款操作

=== 背景描述
课栈贷款业务的机构代偿，学生线下还给了机构，机构线下给了保理，然后维护线上数据

=== 操作方式
. 从svn上pull下代码，svn地址：https://svn.in.dataengine.com/svn/RD/Development/Operation/Order/trunk/order-1.0.1
. 进行maven install:install 确保项目依赖包下载完毕
. 在rkylin-order-core 模块中，resource下有一个offline_result文件，文件中五列分别对应以下信息：用户订单号,用户id,线下还款日期,应还金额,需要还款的还款日。第五项需要还款的还款日内容为：所还年份-月份-15。注意数据格式一致
. 找到工程com.rkylin.order.file.OffLineProcessor类，直接执行main方法即可

== Q6: 某日债权包有问题

=== 背景描述
背景描述:ROP文件服务器不稳定，导致生成的日债权文件不全，需要重新生成

=== 操作方式
. 通过跳板机登录rc@10.117.59.209
. 连接生产ftp，删除掉当日债权文件，债权文件是在t+1日的文件夹内放入t日的债权文件,Example:10月8日债权在ftp上的文件夹是10月9日
. cd /home/rc/huzijian ; vim client/datafile/data2.txt; data2.txt文件有两行，第一行是机构，第二行是日期，日期为t日。
. 删除服务器上的临时文件,rm -rf 2017-10-09
. 运行./day.sh
. 检查ftp上文件是否生成，Ps:生成过程时间比较长，可稍后查看。